export const FONT_LIST = [
  // Sans
  "Arial",
  "Verdana",
  "Tahoma",
  "Trebuchet MS",
  "Helvetica",
  "Gill Sans",
  "Segoe UI",
  "Calibri",
  "Candara",
  "Optima",
  "Inter",
  "Poppins",
  "Montserrat",
  "Raleway",
  "Open Sans",
  "Nunito",
  "Manrope",
  "Outfit",
  "Rubik",
  "Work Sans",
  "Mulish",
  "Urbanist",
  "Quicksand",
  "Josefin Sans",
  "DM Sans",
  "Cabin",
  "Karla",
  "Barlow",
  "Figtree",
  "Hind",
  "Assistant",

  // Serif
  "Times New Roman",
  "Georgia",
  "Garamond",
  "Palatino",
  "Book Antiqua",
  "Baskerville",
  "Cambria",
  "Didot",
  "Bodoni MT",
  "Playfair Display",
  "Merriweather",
  "Lora",
  "Libre Baskerville",
  "Cormorant Garamond",
  "Cinzel",
  "EB Garamond",
  "Crimson Text",
  "Spectral",
  "Alegreya",
  "Vollkorn",
  "Domine",
  "Prata",
  "Cardo",

  // Signature / Script
  "Great Vibes",
  "Dancing Script",
  "Pacifico",
  "Satisfy",
  "Lobster",
  "Alex Brush",
  "Allura",
  "Courgette",
  "Kaushan Script",
  "Marck Script",
  "Parisienne",
  "Sacramento",
  "Tangerine",
  "Yellowtail",
  "Petit Formal Script",
  "Mr Dafoe",
  "Clicker Script",
  "Cookie",
  "Bad Script",
  "Qwigley",
  "Rochester",
  "Italianno",
  "Meddon",
  "Herr Von Muellerhoff",
  "Dynalight",
  "Bilbo",
  "Bilbo Swash Caps",

  // Modern / Display
  "Bebas Neue",
  "Oswald",
  "Anton",
  "Abril Fatface",
  "League Spartan",
  "Archivo Black",
  "Bungee",
  "Righteous",
  "Fredoka",
  "Titan One",
  "Alfa Slab One",
  "Passion One",
  "Black Ops One",
  "Staatliches",

  // Decorative
  "Cinzel Decorative",
  "Unbounded",
  "Monoton",
  "Orbitron",
  "Audiowide",
  "Russo One",
  "Press Start 2P",
  "Permanent Marker",
  "Shadows Into Light",
  "Indie Flower",
  "Patrick Hand",
  "Amatic SC",
  "Caveat",
  "Gloria Hallelujah",

  // Elegant extras
  "Poiret One",
  "Philosopher",
  "Cormorant",
  "Cormorant SC",
  "Marcellus",
  "Sorts Mill Goudy",
  "Old Standard TT",
  "Alice",
  "Forum",
  "Vidaloka",
];
